# Generated by Django 3.0.8 on 2020-12-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_blogpost_followinfo_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followinfo',
            new_name='Infollow',
        ),
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='Pagepost',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='Plike',
        ),
    ]
